#!/usr/bin/env bash
# This script To infinity and beyond indefinitel
trap interrup SIGTERM

interrup()
{
    echo "I am invincible!!!"
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
